version: "3.8"

services:
  localstack:
    image: localstack/localstack:2.3.2
    network_mode: bridge
    environment:
      SERVICES: lambda,sns,s3,sqs,iam
      DEBUG: 1
    ports:
      - 4566:4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    name: caselaw
    external: true
