AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ds-caselaw-ingester

  TNA Caselaw ingester lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TNACaselawIngesterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ds-caselaw-ingester/
      Handler: lambda_function.handler
      Runtime: python3.11
      Architectures:
        - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TNACaselawIngesterFunction:
    Description: "TNA Caselaw Ingester Lambda Function ARN"
    Value: !GetAtt TNACaselawIngesterFunction.Arn
  TNACaselawIngesterFunctionIamRole:
    Description: "Implicit IAM Role created for TNA Caselaw Ingester function"
    Value: !GetAtt TNACaselawIngesterFunctionRole.Arn
