name: Run linter & tests

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
  test:
    env:
      MARKLOGIC_HOST: ""
      MARKLOGIC_USER: ""
      MARKLOGIC_PASSWORD: ""
    name: Run unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements/local.txt
      - run: python -m pytest ds-caselaw-ingester/tests.py
