name: Deploy lambda to AWS (production)

on:
  release:
    types: [published]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_PRODUCTION_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRODUCTION_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: sam build --use-container -m requirements/base.txt
      - run: >
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ds-caselaw-ingester --s3-bucket tna-caselaw-ingester-deploy --capabilities CAPABILITY_IAM --region eu-west-2 --parameter-overrides
          AwsBucketName=${{ vars.AWS_BUCKET_NAME  }}
          EditorialUiBaseUrl=${{ vars.EDITORIAL_UI_BASE_URL  }}
          MarklogicHost=${{ secrets.MARKLOGIC_HOST }}
          MarklogicPassword=${{ secrets.MARKLOGIC_PASSWORD }}
          MarklogicUser=${{ secrets.MARKLOGIC_USER }}
          MaxRetries=${{ vars.MAX_RETRIES  }}
          NotifyApiKey=${{ secrets.NOTIFY_API_KEY }}
          NotifyEditorialAddress=${{ vars.NOTIFY_EDITORIAL_ADDRESS  }}
          NotifyNewJudgmentTemplateId=${{ vars.NOTIFY_NEW_JUDGMENT_TEMPLATE_ID  }}
          NotifyUpdatedJudgmentTemplateId=${{ vars.NOTIFY_UPDATED_JUDGMENT_TEMPLATE_ID  }}
          PublicAssetBucket=${{ vars.PUBLIC_ASSET_BUCKET  }}
          RollbarEnv=${{ vars.ROLLBAR_ENV  }}
          RollbarToken=${{ secrets.ROLLBAR_TOKEN }}
          SqsQueueUrl=${{ vars.SQS_QUEUE_URL }}
